/**
 * The social card.
 *
 * Next merges metadata shallowly, so a page that declares its own `openGraph`
 * replaces the root object entirely rather than adding to it. Any page doing
 * that has to name the image again, and naming it in one place is what keeps
 * the two from drifting apart.
 *
 * `public/og.jpg` is generated by `scripts/build-logo.mjs` from the logo. It is
 * the salon's mark on cream at 1200×630, which is the right card for a brand
 * whose pages are mostly type — a photograph would be better once there is one
 * shot wide enough not to look cropped at timeline size.
 */
export const OG_IMAGE = {
  url: "/og.jpg",
  width: 1200,
  height: 630,
  alt: "Prestige Hair Society",
} as const;
