/**
 * Generate src/lib/supabase/types.ts by introspecting a PostgreSQL database.
 *
 * `supabase gen types` needs Docker, which is not available in every
 * environment, so this reads pg_catalog directly and emits the same
 * `Database` shape the Supabase client expects.
 *
 *   npm run db:types                     # local test database
 *   DATABASE_URL=... npm run db:types    # any other database
 */
import { writeFileSync } from "node:fs";
import { Client } from "pg";

const DATABASE_URL =
  process.env.DATABASE_URL ??
  "postgresql://postgres@localhost:5432/prestige_test";
const OUT = "src/lib/supabase/types.ts";

/** PostgreSQL type -> TypeScript type. */
function tsType(udt: string, enums: Map<string, string[]>): string {
  if (enums.has(udt)) return `Database["public"]["Enums"]["${udt}"]`;
  // Array types are reported by pg as the element type prefixed with an underscore.
  if (udt.startsWith("_")) return `${tsType(udt.slice(1), enums)}[]`;

  switch (udt) {
    case "int2":
    case "int4":
    case "int8":
    case "float4":
    case "float8":
    case "numeric":
      return "number";
    case "bool":
      return "boolean";
    case "json":
    case "jsonb":
      return "Json";
    default:
      // uuid, text, citext, timestamptz, date, time, inet, bpchar, tsrange...
      // all surface as strings over PostgREST.
      return "string";
  }
}

type Column = {
  table: string;
  name: string;
  udt: string;
  nullable: boolean;
  hasDefault: boolean;
  isGenerated: boolean;
};

async function main() {
  const client = new Client({ connectionString: DATABASE_URL });
  await client.connect();

  const { rows: enumRows } = await client.query<{ name: string; labels: string[] }>(`
    -- Cast to text[]: node-pg has no parser for the name[] array type.
    select t.typname as name, array_agg(e.enumlabel::text order by e.enumsortorder) as labels
    from pg_type t
    join pg_enum e on e.enumtypid = t.oid
    join pg_namespace n on n.oid = t.typnamespace
    where n.nspname = 'public'
    group by t.typname
    order by t.typname
  `);
  const enums = new Map(enumRows.map((r) => [r.name, r.labels]));

  const { rows: columns } = await client.query<Column>(`
    select
      c.relname as table,
      a.attname as name,
      format_type(a.atttypid, null) as format,
      t.typname as udt,
      not a.attnotnull as nullable,
      (a.atthasdef and coalesce(ad.adbin::text not like '%nextval%', true)) or a.atthasdef as "hasDefault",
      a.attgenerated <> '' as "isGenerated"
    from pg_attribute a
    join pg_class c on c.oid = a.attrelid
    join pg_namespace n on n.oid = c.relnamespace
    join pg_type t on t.oid = a.atttypid
    left join pg_attrdef ad on ad.adrelid = c.oid and ad.adnum = a.attnum
    where n.nspname = 'public'
      and c.relkind in ('r', 'v', 'm')
      and a.attnum > 0
      and not a.attisdropped
    order by c.relname, a.attnum
  `);

  const { rows: functions } = await client.query<{
    name: string;
    args: string;
    returns: string;
  }>(`
    select
      p.proname as name,
      pg_get_function_arguments(p.oid) as args,
      pg_get_function_result(p.oid) as returns
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.prokind = 'f'
      and p.proname in (
        'available_slots', 'next_available_slot', 'hold_slot', 'book_slot',
        'confirm_booking_paid', 'reschedule_booking', 'release_expired_holds',
        'is_slot_available', 'effective_service_terms'
      )
    order by p.proname
  `);

  await client.end();

  const byTable = new Map<string, Column[]>();
  for (const col of columns) {
    if (!byTable.has(col.table)) byTable.set(col.table, []);
    byTable.get(col.table)!.push(col);
  }

  const lines: string[] = [
    "// AUTOGENERATED by scripts/gen-types.ts -- do not edit by hand.",
    "// Regenerate after a migration with: npm run db:types",
    "",
    "export type Json =",
    "  | string",
    "  | number",
    "  | boolean",
    "  | null",
    "  | { [key: string]: Json | undefined }",
    "  | Json[];",
    "",
    "export type Database = {",
    "  public: {",
    "    Tables: {",
  ];

  for (const [table, cols] of [...byTable].sort(([a], [b]) => a.localeCompare(b))) {
    lines.push(`      ${table}: {`);

    lines.push("        Row: {");
    for (const c of cols) {
      lines.push(`          ${c.name}: ${tsType(c.udt, enums)}${c.nullable ? " | null" : ""};`);
    }
    lines.push("        };");

    lines.push("        Insert: {");
    for (const c of cols) {
      const optional = c.nullable || c.hasDefault || c.isGenerated;
      lines.push(
        `          ${c.name}${optional ? "?" : ""}: ${tsType(c.udt, enums)}${c.nullable ? " | null" : ""};`,
      );
    }
    lines.push("        };");

    lines.push("        Update: {");
    for (const c of cols) {
      lines.push(`          ${c.name}?: ${tsType(c.udt, enums)}${c.nullable ? " | null" : ""};`);
    }
    lines.push("        };");

    lines.push("        Relationships: [];");
    lines.push("      };");
  }

  lines.push("    };");
  lines.push("    Views: Record<string, never>;");

  lines.push("    Functions: {");
  for (const fn of functions) {
    lines.push(`      /** ${fn.name}(${fn.args}) -> ${fn.returns} */`);
    lines.push(`      ${fn.name}: {`);
    lines.push("        Args: Record<string, unknown>;");
    lines.push("        Returns: unknown;");
    lines.push("      };");
  }
  lines.push("    };");

  lines.push("    Enums: {");
  for (const [name, labels] of [...enums].sort(([a], [b]) => a.localeCompare(b))) {
    lines.push(`      ${name}: ${labels.map((l) => `"${l}"`).join(" | ")};`);
  }
  lines.push("    };");
  lines.push("    CompositeTypes: Record<string, never>;");
  lines.push("  };");
  lines.push("};");
  lines.push("");

  // Convenience aliases used throughout the app.
  lines.push("type PublicSchema = Database[\"public\"];");
  lines.push("export type Tables<T extends keyof PublicSchema[\"Tables\"]> =");
  lines.push("  PublicSchema[\"Tables\"][T][\"Row\"];");
  lines.push("export type TablesInsert<T extends keyof PublicSchema[\"Tables\"]> =");
  lines.push("  PublicSchema[\"Tables\"][T][\"Insert\"];");
  lines.push("export type TablesUpdate<T extends keyof PublicSchema[\"Tables\"]> =");
  lines.push("  PublicSchema[\"Tables\"][T][\"Update\"];");
  lines.push("export type Enums<T extends keyof PublicSchema[\"Enums\"]> =");
  lines.push("  PublicSchema[\"Enums\"][T];");
  lines.push("");

  writeFileSync(OUT, lines.join("\n"));
  console.log(
    `Wrote ${OUT}: ${byTable.size} tables, ${enums.size} enums, ${functions.length} functions.`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
